networks:
  free_network:
    driver: bridge

services:
  app:
    image: "php:8.3-apache"
    restart: "always"
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    networks:
      - free_network